### ISSUE TITLE
terminate called after throwing an instance of 'cv::Exception'   what():  OpenCV(4.9.0-dev) /home/c1/opencv/modules/core/src/matrix.cpp:246: error: (-215:Assertion failed) s >= 0 in function 'setSize

### ISSUE THREAD

**Issue by josh-001** [ros-perception/image_transport_tutorials#15]
while publishing my color_image to a topic i am getting this error in the cv::imshow its workkinig fine but while publishing its throwing this error

**Comment by clalancette** [comment]
Please open questions like this on https://robotics.stackexchange.com/questions/tagged/ros, which is our central Question and Answer site.  You'll get a better answer there, and it will be searchable for the future.

Make sure to include a lot of information on what platform you are using, which ROS distribution you are using, and the exact steps you took.
