### ISSUE TITLE
cv_bridge/cv_bridge.h: No such file or directory

### ISSUE THREAD

**Issue by SMRazaRizvi96** [ros-perception/image_transport_tutorials#4]
The

`#include "cv_bridge/cv_bridge.h"
`
command does not recognize the cv_bridge package, even after cloning the `cv_bridge` package inside the same workspace.

**Comment by clalancette** [comment]
#5 should fix it for Rolling.  Can you please give more information about the failure?  Which ROS distribution were you using, which operating system, what full command, and what was the output?

**Comment by jacobperron** [comment]
I think #5 fixed the issue. @SMRazaRizvi96 Please confirm if this is not the case for you.
