### ISSUE TITLE
Build error while trying to build under foxy

### ISSUE THREAD

**Issue by Harshavardhan341** [ros-perception/image_transport_tutorials#6]
While building the package on my system, I am getting the following error:

`CMake Error at CMakeLists.txt:34 (add_executable):
  Target "image_publisher" links to target "cv_bridge::cv_bridge" but the
  target was not found.  Perhaps a find_package() call is missing for an
  IMPORTED target, or an ALIAS target is missing?

CMake Error at CMakeLists.txt:34 (add_executable):
  Target "image_publisher" links to target "image_transport::image_transport"
  but the target was not found.  Perhaps a find_package() call is missing for
  an IMPORTED target, or an ALIAS target is missing?
`

**Comment by clalancette** [comment]
My guess is that you are on Foxy or Galactic.  If so, you need to use the appropriate `foxy` or `galactic` branch; the `main` branch is used for Rolling.

I'm going to close this out, but if you are still having trouble feel free to keep commenting or reopen.

**Comment by Harshavardhan341** [comment]
Yes, that fixed it. Thank you so much.
