### ISSUE TITLE
cv_bridge/cv_bridge.h: No such file or directory

### ISSUE THREAD

**Issue by VickyCas** [ros-perception/image_transport_tutorials#7]
Hello, thank you for making your work public. When i run the code `colcon build`，some errors happened:
> Starting >>> image_transport_tutorials
--- stderr: image_transport_tutorials                             
/home/zhoujialong/HMT/HMT_transport/image_transport_tutorials-main/src/my_subscriber.cpp:16:10: fatal error: cv_bridge/cv_bridge.h: No such file or directory
 #include "cv_bridge/cv_bridge.h"
compilation terminated.
/home/zhoujialong/HMT/HMT_transport/image_transport_tutorials-main/src/my_publisher.cpp:15:10: fatal error: cv_bridge/cv_bridge.h: No such file or directory
 #include "cv_bridge/cv_bridge.h"
compilation terminated.
make[2]: *** [CMakeFiles/my_subscriber.dir/src/my_subscriber.cpp.o] Error 1
make[1]: *** [CMakeFiles/my_subscriber.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
make[2]: *** [CMakeFiles/my_publisher.dir/src/my_publisher.cpp.o] Error 1
make[1]: *** [CMakeFiles/my_publisher.dir/all] Error 2
make: *** [all] Error 2
Failed   <<< image_transport_tutorials [0.44s, exited with code 2]
Summary: 0 packages finished [1.06s]
  1 package failed: image_transport_tutorials
  1 package had stderr output: image_transport_tutorials

However，when i install cv-bridge:
`sudo apt-get install ros-dashing-cv-bridge`, 
it showed:
> Reading package lists... Done
Building dependency tree       
Reading state information... Done
ros-dashing-cv-bridge is already the newest version (2.1.4-1bionic.20210522.014831).
ros-dashing-cv-bridge set to manually installed.
0 upgraded, 0 newly installed, 0 to remove and 86 not upgraded.

Thanks for your kind confirmation.

**Comment by clalancette** [comment]
Note that dashing is no longer maintained, so we don't test anything there anymore.  It is probably the case that a header got renamed at some point and dashing isn't expecting that.  If you are still having problems, please provide a minimum working example on a still maintained distribution (Foxy, Galactic, Humble, or Rolling).

Closing this out for now.

**Comment by cchoirun** [comment]
Hello I'm using ros2 humble, and when i do colcon build, this happened : 
 fatal error: cv_bridge/cv_bridge.h: No such file or directory
    8 | #include "cv_bridge/cv_bridge.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
gmake[2]: *** [CMakeFiles/talker.dir/build.make:76: CMakeFiles/talker.dir/src/publisher_member_function.cpp.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:139: CMakeFiles/talker.dir/all] Error 2
gmake[1]: *** Waiting for unfinished jobs....
gmake: *** [Makefile:146: all] Error 2
---
Failed   <<< cpp_pubsub [6.44s, exited with code 2]

Summary: 0 packages finished [6.56s]
  1 package failed: cpp_pubsub
  1 package had stderr output: cpp_pubsub


Can you solve this ? thank you!
